baseURL = "https://cf.go.vecr.me"
title = "VECR -  A journey"
author = "Vladut Emanuel Cioanca Radu"
paginate = 10
languageCode = "en"
theme = "blowfish"
enableEmoji = true
outputs.home = ["HTML", "RSS", "JSON"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[permalinks]
  [permalinks.page]
    posts = '/:filename/'
  [permalinks.section]
    posts = '/articles/'
    tutorials = '/training/'




