[[main]]
  identifier = "post"
  name = "Post"
  pageRef = "/posts"
  weight = 5

[[main]]
  identifier = "about"
  name = "About"
  pageRef = "/about"
  weight = 10
  
[[main]]
  pre = "github"
  url = "https://github.com/iamvecr"
  weight = 30