# Icons from https://fontawesome.com/

[[main]]
  identifier = "post"
  name = "Post"
  pageRef = "/posts"
  weight = 5

[[main]]
  identifier = "about"
  name = "About"
  pageRef = "/about"
  weight = 10
  
[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/vecr/"
  weight = 30

[[main]]
  identifier = "mastodon" 
  pre = "mastodon"
  url = "https://mas.to/@vecr"
  weight = 31

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://www.x.com/whoisvecr/"
  weight = 32
  
[[main]]
  identifier = "rss"
  pre = "rss"
  url = "/index.xml"
  weight = 33

# FOOTER
# [[footer]]
#   identifier = "post"
#   name = "Post"
#   pageRef = "/posts"
#   weight = 5
