contentTypeName = "posts"
subtitle = ""
colorScheme = "Marvel"
autoSwitchAppearance = true
enableCodeCopy = true
robots = true
copyright = "This work is licensed under CC BY-NC-SA 4.0 unless otherwise noted."


[homepage]
layout = 'profile'
showRecent = true

# [header]
# logo = "logo.webp"

[article]
showDate = false
showWordCount = false
showReadingTime = false

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true