contentTypeName = "posts"
subtitle = ""
colorScheme = "Marvel"
autoSwitchAppearance = true
enableCodeCopy = true
robots = true
copyright = "This work is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) unless otherwise noted."
enableSearch = true


[homepage]
layout = 'profile'
showRecent = false

# [header]


[article]
showDate = false
showWordCount = false
showReadingTime = false

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true